### ISSUE TITLE
Publish Circle Packing Plugin

### ISSUE THREAD

**Issue by philworthy** [winkerVSbecks/varun.ca#10]
Hi. Just wondering if you're planning to publish the circle packing plugin in Figma Community?
Thanks

**Comment by philworthy** [comment]
Thanks Varun, but I don't see the circle packing anywhere in Jali - am I missing something?

**Comment by winkerVSbecks** [comment]
Oh sorry, I thought you meant the other one. No, that was just meant to be an example. I'm actually surprised there isn't a published plugin that does that. You know what, I'll package it up and publish it later this week.

**Comment by philworthy** [comment]
Awesome thank you Varun. What name should I search for? (or are you adding it to Jali?). Hey by the way I get a weird issue in Jali on Figma desktop (MacOS) where it goes blank after I tap the dropdown (it's fine in a browser).

**Comment by winkerVSbecks** [comment]
I submitted it for review yesterday. Should be available here once it is approved https://www.figma.com/community/plugin/843186203578433973

As for Jali, I think there's a bug somewhere. I haven't had time to fix it yet.

**Comment by philworthy** [comment]
Awesome, thank you! It's not up yet but I'll keep an eye out. Much appreciated Varun

**Comment by philworthy** [comment]
Hi @winkerVSbecks just checking in because that plugin URL still shows a 404.
No stress if you decided not to publish, but I thought I'd reach out to let you know incase you didn't notice.

**Comment by winkerVSbecks** [comment]
Hey @philworthy the plugin was rejected. I did an update and resubmitted it this morning. If you are interested I can give you a build that you can try locally with the figma desktop app.

**Comment by philworthy** [comment]
Ah ok that would be great. Thanks Varun.

**Comment by winkerVSbecks** [comment]
Here you go: [build.zip](https://github.com/winkerVSbecks/varun.ca/files/5482264/build.zip)

You can unzip and add it to Figma. You can only do this in the desktop app. 

Go to manage plugins screen, hit the + button to add a new plugin:
<img width="980" alt="Screen Shot 2020-11-03 at 10 31 25 AM" src="https://user-images.githubusercontent.com/42671/98006066-d128c080-1dbf-11eb-8115-503ad37a32ce.png">

Select the manifest file from the build folder:
<img width="714" alt="Screen Shot 2020-11-03 at 10 31 36 AM" src="https://user-images.githubusercontent.com/42671/98006075-d5ed7480-1dbf-11eb-9077-0d19e61190be.png">


It'll show up under the development menu:

<img width="737" alt="Screen Shot 2020-11-03 at 10 29 31 AM" src="https://user-images.githubusercontent.com/42671/98005820-7b541880-1dbf-11eb-9ef9-0c027ca73358.png">

**Comment by philworthy** [comment]
You're awesome, thanks Varun!

**Comment by winkerVSbecks** [comment]
@philworthy finally got published https://www.figma.com/community/plugin/904007992809854059/Pack thanks for your patience
