### ISSUE TITLE
How did you get code syntax highlighting working? | Dark Mode

### ISSUE THREAD

**Issue by arjunkalburgi** [winkerVSbecks/varun.ca#2]
I've been having a lot of trouble with it on my site: 
https://www.arjunkalburgi.com/writing/moving-my-blog-to-gatsby/

Yours looks really great and on-theme!

<img width="763" alt="image" src="https://user-images.githubusercontent.com/8989414/68951632-6816fa00-07b6-11ea-9271-994b8ff07f72.png">

I tried to implement it here but it didn't work at all 
https://github.com/arjunkalburgi/writing/commit/7613dc6ff00a0aaab3a3f78452aa39d6661a638f

**Comment by winkerVSbecks** [comment]
I'm using the `gatsby-remark-prismjs` and `gatsby-remark-code-titles` plugins. They parse the code and apply the appropriate HTML and class names. However, you also need to include a prism theme CSS file. For example `require('prism-themes/themes/prism-base16-ateliersulphurpool.light.css');`

Alternatively you can create your own theme and support dark/light mode https://github.com/winkerVSbecks/varun.ca/blob/master/src/theme/prism-styles.js I based this off of how Gatsby documentation site works.
