### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by erictreacy** [winkerVSbecks/varun.ca#4]
Hi Varun! 👋
Excellent article! Thank you! 
I think there might be a typo in your text though. It doesn't seem like your writing style. Maybe you meant 'shifting'?

![Inkedvarun ca_dark-mode_edit-edit](https://user-images.githubusercontent.com/7545656/70734507-5b64c380-1cda-11ea-9b33-7d3d478abd9c.jpg)

**Comment by winkerVSbecks** [comment]
wow ok 😅 Thank you for pointing this out.
