### ISSUE TITLE
Three ways to create 3D particle effects - MeshLine to Line2

### ISSUE THREAD

**Issue by dandesdev** [winkerVSbecks/varun.ca#41]
Since MeshLine is no longer supported and its not an official part of threejs, is It possible to do the same thing with the line2 geometries from drei? more specifically, CatmullRomLine? I am struggling with this and it seems to me that it is not possible to animate it as you did with MeshLine.

**Comment by winkerVSbecks** [comment]
Maybe, the API is pretty different but you might be able to replicate it. 
Drei also has a utility for line: https://drei.pmnd.rs/?path=/story/abstractions-line--cubic-bezier

I think I tried using the Drei version but, I don't have the code anymore.

That said, I do have a patched version of Meshline that should still work with Three.js: https://github.com/winkerVSbecks/solarstorm/tree/main/src/MeshLine

**Comment by dandesdev** [comment]
Hi again! How can I use MeshLine with Typescript? I tried:

```
import * as meshLine from "../../MeshLine";

extend(meshLine);

declare module "@react-three/fiber" {
  interface ThreeElements {
    meshLine: Object3DNode<meshLine.MeshLine, typeof meshLine.MeshLine>;
    meshLineMaterial: Object3DNode<
      meshLine.MeshLineMaterial,
      typeof meshLine.MeshLineMaterial
    >;
  }
}
```
and then my component returns like yours something like this:

```
    <mesh>
      <meshLine ref={line} attach="geometry" points={positions} />
      <meshLineMaterial
        attach="material"
        transparent
        lineWidth={width}
        color={new THREE.Color(color)}
      />
    </mesh>
```

But TS is complaining "Type '{ ref: any; attach: string; points: Vector3[]; }' is not assignable to type 'Object3DNode<MeshLine, typeof MeshLine>'.
  Property 'points' does not exist on type 'Object3DNode<MeshLine, typeof MeshLine>'. Did you mean '_points'?ts(2322)" and similarly "Type '{ attach: string; transparent: true; lineWidth: number; color: Color; }' is not assignable to type 'Object3DNode<MeshLineMaterial, typeof MeshLineMaterial>'.
  Property 'color' does not exist on type 'Object3DNode<MeshLineMaterial, typeof MeshLineMaterial>'.ts(2322)". I don't understand why this is happening.

**Comment by winkerVSbecks** [comment]
Sorry I have no idea. I've never tried using R3F with TS. 

I'm guessing that the meshline type is missing the `points` prop.

**Comment by winkerVSbecks** [comment]
Okay I think I know why. The meshline implementation uses `Object.defineProperties` to extend `this`. That's where the public API is attached. IMO you're going to have to define types for it instead of using `typeof meshLine.MeshLine`
